### ISSUE TITLE
Tổng quan về Ansible

### ISSUE THREAD

**Issue by quynhvuongg** [quynhvuongg/Ansible#1]
# Ansible

## Giới thiệu về Ansible

- Ansible là một IT automation tool hỗ trợ cấu hình các hệ thống, triển khai phần mềm và điều phối các tác vụ CNTT nâng cao hơn như triển khai liên tục hoặc cập nhật thời gian ngừng hoạt động.
- Ansible được phát triển bởi Michael DeHaan năm 2012. Ansible được tạo ra với mục đích là: simplicity, security, reliablity and easy to use.
- Ansible chủ yếu chạy trong chế độ push sử dụng SSH, nghĩa là ta sẽ push các configurations từ server tới các agent. Nhưng ta cũng có thể chạy ansible sử dụng ansible-pull, nghĩa là ta có thể cài đặt ansible lên mỗi agent, sau đó download các playbook từ server về và chạy.

## Cài đặt Ansible

```sh
$ sudo apt install ansible
$ sudo apt install openssh-server 
```

## Ansible Architecture 

![image](/uploads/8052c0eed2d3600dbd1b995e220ea177/image.png)

Tại 1 hoặc nhiều các trung tâm điều khiển ta có thể phát ra các lệnh hoặc 1 tập lệnh thông qua playbook để chạy trên các remote servers.

**_Inventory_**: là file chứa thông tin của các remote server, nơi mà tasks sẽ được thực thi.

```sh
[webservers]
www1.example.com
www2.example.com

[dbservers]
db0.example.com
db1.example.com
```

**_Playbook _**: là file định dạng bằng yml mô tả scrips cho từng host.

**_Ansible config _**: là file cấu hình cho ansible cho phép người dùng cấu hình ansible phù hợp với những cài đặt trong môi trường của bạn.

**_Modules_**

Modules là nơi thực hiện các công việc thực sự trong ansible, chúng là những gì được thực hiện trong mỗi playbook task.

Mỗi module sẽ có các tham số truyền vào là khác nhau, và hầu như tất cả các module đều có tham số theo dạng "key=value", các tham số cách nhau bởi dấu cách. Ngoài ra cũng có 1 số module không có tham số như ping...

### Ansible config

Hai cách để cấu hình cho Ansible: dùng biến môi trường và sử dụng file ansible.cfg

- Config sử dụng biến môi trường: Ta có thể sử dụng hầu hết configuration parameters trực tiếp thông qua các biên môi trường bằng cách thêm tiền tố ANSIBLE_ ở đầu mỗi parameter (tên parameters phải là chữ hoa)

```sh
$ export ANSIBLE_SUDO_USER=root
```
- Config sử dụng file ansible.cfg: Sử dụng Ansible paparmeter để config

   - hostfile: chỉ ra đường dẫn của inventory file.
   - library: bất cứ khi nào ta yêu cầu ansible thực hiện 1 hành động nào đó, dù cho đó là 1 hành động trên local hay tới 1 remote server, thì ansible cũng đều phải sử dụng 1 module nào đó để thực hiện. Parameter library sẽ chỉ tới đường dẫn của thư mục chứa các Ansible module. Ví dụ như: library = /usr/share/ansible.
    - forks: số lượng process mặc định mà ta muốn Ansible thực hện song song, mặc định forks=5, có nghĩa là nếu ta muốn thực thi 1 task trên 10 remote servers thì ansible sẽ sinh ra 5 process để yêu cầu thực hiện task trên 5 remote servers cùng lúc, còn 5 servers còn lại sẽ phải đợi khi process yêu cầu thực hiện task được giải phóng thì ansible mới thực hiện tiếp task đó trên các server còn lại.
    - sudo_user: chỉ định user mặc định.
    - remote_port: sử dụng để chỉ định port cho SSH connection, mặc định là 22.
    - host_key_checking: được dùng để disable việc kiểm tra SSH host key, mặc định là True.
    - timeout: là giá trị cho timeout của SSH connection, mặc định là 60s.
    - log_path: theo mặc định thì ansible không log lại gì, nhưng nếu ta muốn đưa output của Ansible vào 1 logfile thì ta có thể sử dụng parameter log_path chỉ tới đường dẫn của file mà ta muốn lưu log.
    - ...

### Inventory file

- Inventory file chứa các thông tin về hosts mà ta sẽ thực hiện các task trên đó. Theo mặc định, ansible sẽ coi file có `/etc/ansible/hosts` là inventory file mặc định. Nhưng việc ta không nên sử dụng file mặc định này, mà nên tạo các inventory file khác nhau cho mỗi project, sau đó ta có thể truyền vào khi chạy câu lệnh ansible với option `-i`

```sh
$ ansible -i ./hosts 
```
- Nó là 1 file JSON hoặc INI file. Nhưng hầu hết các trường hợp thì ta thường dùng INI file vì nó có cấu trúc vô cùng đơn giản. Ta chỉ dùng JSON khi inventory file cần được generate động.

**_Option config_**
Một số parameter sử dụng trong config inventory file

Parameter chung:

- ansible_host: cho phép ta sử dụng 1 tên khác để làm việc với host, thay vì sử dụng ip hoặc hostname trong các playbook. Điều này giúp ta không phải thay đổi tên host trong các playbook khi ip hay hostsname của nó thay đổi. 
Ví dụ: vm1 - ansible_host=192.168.122.140
- ansible_user: user để login vào remote host thông qua SSH. 
Ví dụ: ansible_user=vm1 sẽ tương đương với ssh vm1@192.168.122.140
- ansible_port: port mà SSH server nghe trên remote host. Ta cũng có thể sử dụng thông qua bí danh bằng cách `hostname:port`

Parameter cho SSH:

- ansible_ssh_private_key_file: SSH key file được sử dụng để log in. 
- ansible_ssh_pass: nếu user mà ta đang sử dụng để connect tới remote host yêu cầu password.

Parameter cho user kết nối:

- ansible_become: tương đương với ansible_sudo hoặc ansible_su, cho phép user hiện tại sử dụng quyền sudo hoặc su.
- ansible_become_method: method được dùng để chạy với quyền superuser. Mặc định là sudo, nhưng ta cũng có thể chỉnh lại thành su.

### Playbook

- Playbook là 1 file được định dạng bằng YAML format, có cú pháp đơn giản miêu tả những hosts nào được config, và 1 danh sách các tasks hoặc command mà ta sẽ được thực hiện trên những host đó.
- Mỗi playbook bao gồm 1 hoặc nhiều 'plays' trong 1 list. Mỗi play phải chứa các thành phần sau:
   - 1 list hosts để config
   - 1 list tasks để thực thi trên các hosts trong list trên.
- Mục đích của play là map host hoặc 1 nhóm các host với 1 số roles xác định, mỗi role sẽ thực hiện các task nào đó. Ở mức độ cơ bản, 1 task đơn giản chỉ là 1 lời gọi tới 1 ansible module.

```yml
- name: set Prometheus system
  hosts: localhost
  tasks:
    - name: copy  Prometheus docker
      copy:
        src: /home/sand/quynh/Prometheus/ConfigurationFiles
        dest: /home/sand/test/
    - name: docker compose
      docker_service:
        project_src: /home/sand/test/ConfigurationFiles                                                         
```

   - hosts: nơi liệt kê host hoặc tên nhóm các hosts mà ta muốn thực hiện các task trong mục tasks. Trường hosts này là bắt buộc đối với mỗi playbook. Khi thực hiện playbook, ansible sẽ lấy tên host hoặc host group mà ta khai báo trong option hosts này, sau đó tìm trong inventory file, nếu như không có host hoặc goup host nào khớp với host hoặc group hosts mà ta đã khai báo trong playbook thì ansible sẽ bỏ qua tất cả các task trong playbook đó.
   - tasks: là 1 danh sách các hành động mà bạn muốn thực hiện. Trường tasks này bao gồm các thành phần: tên của task (name), các module sẽ được thực thi, và các tham số cần thiết cho các module đó.

**Comment by quynhvuongg** [comment]
![image](https://user-images.githubusercontent.com/61721493/82292505-3be26d00-99d5-11ea-95c4-4ebd553556fb.png)

![image](https://user-images.githubusercontent.com/61721493/82292575-59afd200-99d5-11ea-8de1-b78b245fe344.png)


![image](https://user-images.githubusercontent.com/61721493/82292721-94196f00-99d5-11ea-9f13-192b8afbffee.png)

**Comment by quynhvuongg** [comment]
playbook1.yml
```yml
- name: set Prometheus system
  hosts: localhost
  tasks:
    - name: copy prometheus.yml
      copy:
        src: /home/quynh/Prometheus/ConfigurationFiles/prometheus.yml
        dest: /home/quynh/Ansible/test/

    - name: copy rule_files
      copy:
        src: /home/quynh/Prometheus/ConfigurationFiles/rule_files
        dest: /home/quynh/Ansible/test/

    - name: Prometheus container
      docker_container:
        name: Prometheus
        image: prom/prometheus
        state: present
        volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus_data:/prometheus
          - ./rule_files:/etc/prometheus/rule_files
        exposed_ports:
          - 9090

    - name: node-exporter container
      docker_container:
        name: node-exporter
        image: prom/node-exporter
        state: present
        exposed_ports:
          - 9100

    - name: grafana container
      docker_container:
        name: grafana
        image: grafana/grafana
        state: present
        volumes:
          - grafana_data:/var/lib/grafana
        exposed_ports:
          - 3000
```
![image](https://user-images.githubusercontent.com/61721493/82296470-6fc09100-99db-11ea-840c-3024160c31a7.png)

![image](https://user-images.githubusercontent.com/61721493/82296614-a5fe1080-99db-11ea-8e0a-21cb46a0f7b5.png)

![image](https://user-images.githubusercontent.com/61721493/82296635-aeeee200-99db-11ea-8d9e-1db9adba1229.png)

![image](https://user-images.githubusercontent.com/61721493/82296661-b910e080-99db-11ea-987d-f942a606be64.png)
